import type { Locale } from "@/lib/i18n";

const copy = {
  pt: {
    badge1: "São Paulo · BR",
    badge2: "Techno · dark · glitch",
    heroTitle: "Glitch, pista, sequência.",
    heroLead:
      "Tulio — DJ e produtor. Sets gravados, live sets, releases e arquivo visual. Tudo publicado para quem curte, contrata ou divulga.",
    heroParagraphs: [
      "Túlio atua conectado à cultura underground, construindo experiências através de seus sets. Suas apresentações são desenvolvidas de forma progressiva, explorando tensão, atmosfera, groove e dinâmica para criar uma conexão contínua com a pista. Cada set é construído como uma narrativa, em que seleção musical, sensibilidade e leitura de pista conduzem a experiência do início ao fim.",
      "Sua identidade sonora tem o House como principal ponto de partida, mas se expande por diferentes vertentes e referências da música eletrônica. Essa amplitude faz parte de sua pesquisa musical e aparece de maneira fluida em seus sets, onde diferentes sonoridades, texturas e influências se encontram sem perder coerência. Mais do que se limitar a um gênero específico, sua seleção é guiada pela narrativa, pela energia e pelo momento da pista.",
      "Ao longo de sua trajetória, apresentou-se em diferentes cenários da música eletrônica brasileira, incluindo a pista Sinkrö do Festival Universo Paralello e o D-Edge, em São Paulo, além de performances em Fernando de Noronha e Jericoacoara.",
    ],
    ctaPrimary: "Ouvir sets",
    ctaSecondary: "Ver galeria",
    trusted: "Som também em",
    featuresEyebrow: "O site",
    featuresTitle: "Três portas para a pista.",
    featuresLead:
      "Escuta, disco e imagem — sem login, sem paywall. Só o que importa para fã, promotor e imprensa.",
    f1index: "01 — Sets",
    f1label: "Escuta",
    f1title: "Gravações secas, prontas para volume alto",
    f1body:
      "Player com fila, capas em alta e datas de cada set. Para ouvir antes do show ou depois da noite.",
    f2index: "02 — Releases",
    f2label: "Discografia",
    f2title: "Música autoral nos apps que você já usa",
    f2body:
      "Spotify, Bandcamp, SoundCloud — links oficiais, arte e créditos num só lugar.",
    f3index: "03 — Arquivo",
    f3label: "Visual",
    f3title: "Foto e vídeo da cabine ao floor",
    f3body:
      "Galeria por festa e data. Download quando liberado. Presskit com rider para booking.",
    stepsEyebrow: "Fluxo",
    stepsTitle: "Da cabine ao booking.",
    step1n: "01",
    step1t: "Ouça um set",
    step1b: "Entre em Sets, escolha uma sessão e deixe o player rodar — fila, shuffle, capa.",
    step2n: "02",
    step2t: "Siga o release",
    step2b: "Discografia com links diretos — salve, compartilhe, playlist.",
    step3n: "03",
    step3t: "Press e datas",
    step3b: "Presskit, fotos em alta, rider técnico e próximas datas no menu.",
    quotesEyebrow: "Depoimentos",
    quotesTitle: "Quem já passou pela cabine.",
    q1: "Set denso, transição limpa — a pista ficou até o último segundo.",
    q1n: "Curadoria",
    q1r: "Clube · SP",
    q2: "Press impecável, rider claro. Fechamos a data sem dez e-mails.",
    q2n: "Produção",
    q2r: "Festival",
    faqEyebrow: "FAQ",
    faqTitle: "Antes de fechar a data.",
    faqLead:
      "Contratação, rider, onde ouvir e como baixar foto — o que promotores e fãs perguntam primeiro.",
    faq1q: "Como contratar Tulio para um set?",
    faq1a:
      "Presskit no site, próximas datas no menu inferior ou contato via redes. Rider técnico e fotos oficiais inclusos.",
    faq2q: "Onde ouço os sets completos?",
    faq2a: "Na página Sets — player integrado. Novas gravações entram na mesma fila.",
    faq3q: "Tem live set em vídeo?",
    faq3a: "Sim, na página Live Sets — gravações de pista quando publicadas.",
    faq4q: "Posso baixar fotos para flyer ou imprensa?",
    faq4a:
      "Quando marcadas para download na galeria ou presskit. Várias fotos em ZIP de uma vez.",
    ctaTitle: "Entra na pista hoje.",
    ctaLead: "Sets, releases e arquivo. Se não prender em uma sessão, volta na próxima.",
    ctaPrimary2: "Ouvir sets",
    ctaSecondary2: "Próximas datas",
    bioEyebrow: "Biografia",
    chipSets: "▶ queue · player",
    chipRelease: "Bandcamp · Spotify",
    chipArchive: "press · ZIP",
  },
  en: {
    badge1: "São Paulo · BR",
    badge2: "Techno · dark · glitch",
    heroTitle: "Glitch, floor, sequence.",
    heroLead:
      "Tulio — DJ and producer. Recorded sets, live sets, releases and visual archive. Built for listeners, promoters and press.",
    heroParagraphs: [
      "Túlio atua conectado à cultura underground, construindo experiências através de seus sets. Suas apresentações são desenvolvidas de forma progressiva, explorando tensão, atmosfera, groove e dinâmica para criar uma conexão contínua com a pista. Cada set é construído como uma narrativa, em que seleção musical, sensibilidade e leitura de pista conduzem a experiência do início ao fim.",
      "Sua identidade sonora tem o House como principal ponto de partida, mas se expande por diferentes vertentes e referências da música eletrônica. Essa amplitude faz parte de sua pesquisa musical e aparece de maneira fluida em seus sets, onde diferentes sonoridades, texturas e influências se encontram sem perder coerência. Mais do que se limitar a um gênero específico, sua seleção é guiada pela narrativa, pela energia e pelo momento da pista.",
      "Ao longo de sua trajetória, apresentou-se em diferentes cenários da música eletrônica brasileira, incluindo a pista Sinkrö do Festival Universo Paralello e o D-Edge, em São Paulo, além de performances em Fernando de Noronha e Jericoacoara.",
    ],
    ctaPrimary: "Listen to sets",
    ctaSecondary: "View gallery",
    trusted: "Also on",
    featuresEyebrow: "The site",
    featuresTitle: "Three doors to the floor.",
    featuresLead:
      "Listen, discography and visuals — no login, no maze. What fans, bookers and press actually need.",
    f1index: "01 — Sets",
    f1label: "Listen",
    f1title: "Dry recordings, ready loud",
    f1body:
      "Queued player, sharp artwork and set dates. Before the gig or after the night.",
    f2index: "02 — Releases",
    f2label: "Discography",
    f2title: "Original music on your apps",
    f2body: "Spotify, Bandcamp, SoundCloud — official links, art and credits in one place.",
    f3index: "03 — Archive",
    f3label: "Visual",
    f3title: "From booth to dancefloor",
    f3body: "Gallery by party and date. Downloads when enabled. Presskit and rider for booking.",
    stepsEyebrow: "Flow",
    stepsTitle: "From booth to booking.",
    step1n: "01",
    step1t: "Play a set",
    step1b: "Open Sets, pick a session and let the player run — queue, shuffle, artwork.",
    step2n: "02",
    step2t: "Follow releases",
    step2b: "Discography with direct links — save, share, playlist.",
    step3n: "03",
    step3t: "Press & dates",
    step3b: "Presskit, hi-res photos, technical rider and upcoming dates in the menu.",
    quotesEyebrow: "Voices",
    quotesTitle: "From the booth.",
    q1: "Dense set, clean transitions — the floor stayed until the last second.",
    q1n: "Programming",
    q1r: "Club · SP",
    q2: "Impeccable press, clear rider. We locked the date without ten emails.",
    q2n: "Production",
    q2r: "Festival",
    faqEyebrow: "FAQ",
    faqTitle: "Before you lock the date.",
    faqLead: "Booking, rider, where to listen and photo downloads — what bookers and fans ask first.",
    faq1q: "How do I book Tulio?",
    faq1a: "Presskit on the site, upcoming dates in the bottom menu, or socials. Rider and official photos included.",
    faq2q: "Where do I hear full sets?",
    faq2a: "On the Sets page — built-in player. New recordings join the same queue.",
    faq3q: "Are there live video sets?",
    faq3a: "Yes — Live Sets page when published.",
    faq4q: "Can I download photos for flyers or press?",
    faq4a: "When marked downloadable in gallery or presskit. Multiple photos as one ZIP.",
    ctaTitle: "Hit the floor today.",
    ctaLead: "Sets, releases and archive. If one session doesn't stick, come back for the next.",
    ctaPrimary2: "Listen to sets",
    ctaSecondary2: "Upcoming dates",
    bioEyebrow: "Biography",
    chipSets: "▶ queue · player",
    chipRelease: "Bandcamp · Spotify",
    chipArchive: "press · ZIP",
  },
} as const;

export type NocturnaHomeCopy = (typeof copy)["en"];

export function getNocturnaHomeCopy(locale: Locale): NocturnaHomeCopy {
  if (locale === "pt") return copy.pt;
  return copy.en;
}
